import { cibGit, cibGithub } from '@coreui/icons'
import CIcon from '@coreui/icons-react'
import { CContainer, CNavLink } from '@coreui/react'
import React from 'react'
import { useDispatch } from 'react-redux'
import { updateNpub } from 'src/redux/features/siteNavigation/slice'

const NostrapediaAbout = () => {
  const dispatch = useDispatch()
  const setCurrentNpub = (newNpub) => {
    dispatch(updateNpub(newNpub))
  }
  return (
    <>
      <CContainer>
        <center>
          <h3>About Nostrapedia</h3>
        </center>
        <br />
        <br />
        <div>
          Nostrapedia is an implementation of{' '}
          <a
            target="_blank"
            href="https://github.com/nostr-protocol/nips/blob/master/54.md"
            rel="noreferrer"
          >
            NIP-54
          </a>{' '}
          with a focus on bringing web of trust to nostr. See also{' '}
          <a target="_blank" href="https://wikifreedia.lol" rel="noreferrer">
            Wikifreedia
          </a>{' '}
          and{' '}
          <a target="_blank" href="https://wikistr.com" rel="noreferrer">
            Wikistr
          </a>
          .
        </div>
      </CContainer>
    </>
  )
}

export default NostrapediaAbout

/*
<br />
<br />
<center>
  <h4>Web of Trust (WoT) scores</h4>
</center>
<div>
  <p>
    Alice's WoT score is equal to the number of users who meet two criteria: you follow that
    user, and that user follows Alice. This method is the same or similar to the method used
    by{' '}
    <a target="_blank" href="https://coracle.social" rel="noreferrer">
      Coracle
    </a>{' '}
    and{' '}
    <a target="_blank" href="https://wikifreedia.lol" rel="noreferrer">
      Wikifreedia
    </a>
    , with the caveat that Nostrapedia does not (yet) adjust the score downwards slightly
    based on mute lists.
  </p>
  <p>
    The WoT is quite useful for screening out noise generated by bots and other egregiously
    bad actors. However, the WoT score has several disadvantages:
    <li>
      Any profile more than two hops away from you will have a WoT score of zero. Any
      profiles more than two hops away will be missed.
    </li>
    <li>The WoT score does not differentiate based on context.</li>
    <li>
      The WoT score is still a bit of a popularity contest which rewards people for spending
      time on social media and overlooks those who don't.
    </li>
  </p>
</div>
<br />
<br />
<center>
  <h4>Influence scores</h4>
</center>
<div>
  <p>
    The influence score is designed to address the above shortcomings. Like the WoT above,
    the influence score as currently implemented is based on follows and mutes. However, the
    algorithm is designed to synthesize data from multiple sources at once, including
    contextual trust attestations. For details of how the influence score is calculated, see
    the Influence Scores tab on any individual profile page.
  </p>
  <p>
    Advantages of the influence score over the WoT score include:
    <li>
      The influence score extends beyond 2 hops, whereas the WoT score (as frequently
      implemented) is zero for anyone more than 2 hops away.
    </li>
    <li>
      The influence score can readily synthesize data from multiple sources. Proxy trust
      data (follows, mutes, likes, etc) and explict contextual attestations can be used
      together in the same calculation to generate a single influence score.
    </li>
    <li>
      Distinct influence scores can be generated for each distinct purpose and context of
      interest.
    </li>
  </p>
  <p>
    Disadvantages of the influence score include:
    <li>
      Influence score calculations are computationally expensive and take too long to do
      them all on the fly. The provision of readily available influence scores as a service
      may one day become an important business model.
    </li>
    <li>
      There are multiple adjustable parameters for calculation of influence scores, the
      optimization of which may feel burdensome for most users. Fortunately, default
      settings for these parameters will work well enough in most situations.
    </li>
  </p>
</div>
<br />
<br />
<center>
  <h4>Interpretation of proxy indicators of trust</h4>
</center>
<br />
<br />
<div>
  <p>
    Q: How does the influence score synthesize proxy trust data (follows, mutes, likes, etc)
    and contextual trust attestations into a single score?
  </p>
  <p>
    A: Through the process of <i>interpretation</i>. Proxy data, such as a follow or a like,
    is "interpreted" <i>as if</i> it were an explicit contextual trust attestation.
  </p>
  <p>
    As we all know, proxy indicators are not <i>actual</i> statements of trust.
    Nevertheless, we use them as if they were, especially if that's all we have to go on.
    For this reason, interpreted data is typicaly assigned a very low confidence. Currently,
    a follow is interpreted as a statement of trust in all contexts, with a score of 100,
    but with a confidence of only (5% ?), which is a parameter than can be adjusted by the
    user doing the interpretation (i.e. YOU).
  </p>
</div>
*/
